### ISSUE TITLE
Features Todo list

### ISSUE THREAD

**Issue by ameliaikeda** [R-a-dio/Android-app#10]
General Todo list for the features. Swiping between them would be ideal. Check them off as they are done. I'll link them all to their own issues when they are made.
- [x] Streaming Functionality
- [ ] News Posts
- [ ] News Comments
- [ ] Stats listing (All images are SVGs, too)
- [x] Full queue listing
- [x] Full Last played list
- [ ] Faving songs
- [x] Song Searching
- [x] Song Requesting
- [x] DJ Notifications (see #9)
